### ISSUE TITLE
Could not load model with any of the following classes

### ISSUE THREAD

**Issue by ibrahim737701** [databrickslabs/dolly#65] opened 2023-04-13 08:30 UTC
import torch
from transformers import pipeline

generate_text = pipeline(model="databricks/dolly-v2-12b", torch_dtype=torch.bfloat16, trust_remote_code=True, device_map="auto")
  This is leading to the error :-

 in infer_framework_load_model
  raise ValueError(f"Could not load model {model} with any of the following classes: {class_tuple}.")
ValueError: Could not load model databricks/dolly-v1-6b with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForCausalLM'>, <class 'transformers.models.gptj.modeling_gptj.GPTJForCausalLM'>).

**Comment by maziyarpanahi** [comment] 2023-04-13 09:04
I just used that model, not in the pipeline, but directly. 

```python
tokenizer = AutoTokenizer.from_pretrained("databricks/dolly-v2-12b", padding_side="left")
model = AutoModelForCausalLM.from_pretrained("databricks/dolly-v2-12b", device_map="auto", trust_remote_code=True, torch_dtype=torch.bfloat16)
```
I would say maybe you need to install `transformers` from the `main` branch just to be sure everything is the latest. (if this is not an issue on its own)

**Comment by ibrahim737701** [comment] 2023-04-13 11:45
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them. Alternatively, make sure you have `safetensors` installed if the model you are using offers the weights in this format.

This is coming when i tried yours

**Comment by srowen** [comment] 2023-04-13 13:33
I believe this is a duplicate of https://github.com/databrickslabs/dolly/issues/60

**Closed by srowen** 2023-04-13 13:33 UTC

**Comment by FurkanGozukara** [comment] 2023-04-13 21:45
@ibrahim737701 sorunu çözdün mü

**Comment by ibrahim737701** [comment] 2023-04-14 06:27
input_shape = input_ids.size()
                  ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'size'
