### ISSUE TITLE
Is it possible to utilize NCasT4_v3-series clusters?  

### ISSUE THREAD

**Issue by jdorocak** [databrickslabs/dolly#35] opened 2023-03-29 14:15 UTC
It seems like the cluster has plenty of memory available, but I'm getting the following error.  "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 3; 15.75 GiB total capacity; 15.16 GiB already allocated; 37.62 MiB free; 15.16 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"

**Comment by vadirajmkulkarni** [comment] 2023-03-29 17:44
I'm facing the same error when running on NC24s_v3 cluster. IT has 448GB of memory & 4 GPUs

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 15.78 GiB total capacity; 14.85 GiB already allocated; 147.50 MiB free; 14.85 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by lavarith** [comment] 2023-03-29 22:49
@Joe-Long does the image you use matter for this? I've used A100s, but got the same error.

**Comment by srowen** [comment] 2023-03-30 01:14
I don't think NVLINK is required, but, you will need a lot of VM RAM to load, and enough GPU mem (or deepspeed tweaks) to get smaller instances working. Indeed see the link above. 

A100 instances should be fine, what is giving you CUDA OOM? did you change settings?

**Comment by lavarith** [comment] 2023-03-30 01:23
It's a 40gb a100. Each process gets a message that says something like it's trying to allocate 22 Gb when it's already allocated 22 Gb.

I used exactly the default settings with deep speed although I'm running it on a pytorch cuda image and not yet on databricks. But that's the only difference so I don't see why that should matter.

**Comment by srowen** [comment] 2023-03-30 01:28
I also don't think that would matter. It runs fine for me as is on Databricks. 8 A100s right? Maybe you have slightly different pytorch or CUDA versions? Any modifications at all? Compare for reference https://docs.databricks.com/release-notes/runtime/12.2ml.html

**Comment by lavarith** [comment] 2023-03-30 01:33
I tried with 2 to start with. I assumed it should work but be slower.

I'll ensure those versions match. Otherwise everything else is the same

**Comment by srowen** [comment] 2023-03-30 02:09
It won't affect this, as you have a fixed per-device batch size. You were running with 8 when you set num_gpus to 8 though right?

**Comment by lavarith** [comment] 2023-03-30 02:27
I hadn't set it to 8 GPUs yet with my latest setup that now uses deep speed. I've only tried 2 GPUs. Should I try 8?

**Comment by srowen** [comment] 2023-03-30 02:40
Wait, you weren't using deepspeed? Of course, you have to have that! Use all 8 GPUs. Please use the training exactly as given if you're going to report issues

**Comment by lavarith** [comment] 2023-03-30 09:32
I'll try 8 GPUs this morning.

**Comment by vadirajmkulkarni** [comment] 2023-03-30 10:31
@srowen The NC24s_v3 cluster has 448GB CPU memory & 4 GPUs with 16GB memory each. I guess the issue is with the GPU memory. We need minimum of 24GB of GPU memory right? Any tweaks to run this on 16GB GPU memory?

**Comment by srowen** [comment] 2023-03-30 15:48
You might fit in 16GB with more deepspeed config; try enabling parameter offload too for example. I don't think that's the design goal of the training script in this repo, but you're welcome to try. I'd reach for A10 or A100 of course, not T4.

**Comment by lavarith** [comment] 2023-03-30 16:11
The only difference from the code example is that I'm using the following image and that it runs on vertex ai instead of databricks.
pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime

**Comment by srowen** [comment] 2023-03-30 16:47
I'm kind of losing track of what code you're running how on what instances. For example, I don't know what else you tried changing to get it working on 16GB V100s? maybe needs even more config. I think this may be out of scope for this repo.

**Comment by lavarith** [comment] 2023-03-30 16:50
The v100 problem was someone else. I've always been training on A100s

**Comment by srowen** [comment] 2023-03-30 20:04
I see, we're mixing conversations - OP mentioned T4 and others mentioned V100.
I don't know what the issue is. I wonder if you can start over with the current code? if you can't run on DB, where it does work fine, maybe make the minimal modifications possible to avoid introducing an error.

To double check, you are using deepspeed right? that is required.

**Comment by srowen** [comment] 2023-03-30 20:32
Ah ok. Databricks would be on 1.13. could be it

**Closed** 2023-04-03 13:55 UTC
