### ISSUE TITLE
Please clarify the License Policy

### ISSUE THREAD

**Issue by JayLiangs** [databrickslabs/dolly#206] opened 2023-07-26 08:08 UTC
Hi DataBricks,

I am not sure which license shall be applied to the Dolly-v2-12b so that I cannot give proper credits to your guys when I distribute your model.

In your Model View(https://github.com/databrickslabs/dolly#model-overview), it states that, dolly-v2 -12b applies CC-BY-SA, but do not specify the specifical version of CC-BY-SA. As you know, there is four versions of CC-BY-SA (See https://opendefinition.org/licenses/cc-by-sa/). What makes me more confused is that the LICENSE shows Apache 2.0 License text.

So just clarify the license applied to the Dolly-v2-12b model and many thanks to you

**Comment by srowen** [comment] 2023-07-28 11:35
Duplicate of https://huggingface.co/databricks/dolly-v2-12b/discussions/86
No, it says that the Dolly 15K dataset used for fine-tuning is licensed as CC-BY-SA 3.0, and that is elaborated at https://huggingface.co/datasets/databricks/databricks-dolly-15k
The model card says the model itself (weights) are MIT licensed.

**Closed as completed by srowen** 2023-07-28 11:35 UTC
